[package]
name = "inclusion-ui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
rust-embed = { version = "6.2.0", features = ["warp-ex"] }
