#!/bin/bash
set -e

# Check style
cargo fmt --all -- --check

# Lint it
cargo clippy --all-targets --all-features -- -D warnings
#cargo clippy --all-targets --all-features

# Test it
cargo test

# Build it
cargo build --release
